apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lkristie-poi-map-app-dev
  annotations:
    argocd/app-name: lkristie-poi-map-app-dev
    backstage.io/kubernetes-id: lkristie-poi-map-app
    backstage.io/kubernetes-namespace: lkristie
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-deploy/lkristie-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/dev-pipelines/ns/lkristie/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/k8s/ns/lkristie/deployments/lkristie-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.a1jxqhzp.eastus2.aroapp.io/#https://github.com/rhdh-deploy/lkristie-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://lkristie-poi-map-app-lkristie.apps.a1jxqhzp.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/lkristie"
  system: workshop-system-lkristie
  consumesApis:
    - gateway-api-lkristie
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-lkristie
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/lkristie"
